/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate Policy
         * @description Run illustrative scoring. CPU work is offloaded to a thread pool.
         */
        post: operations["simulate_policy_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulate/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Presets
         * @description Named scenario defaults for the UI.
         */
        get: operations["list_presets_simulate_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** QuintileImpact */
        QuintileImpact: {
            /** Quintile */
            quintile: string;
            /** Income Share */
            income_share: number;
            /** Tax Change Share */
            tax_change_share: number;
            /** Avg Tax Change Pct Income */
            avg_tax_change_pct_income: number;
        };
        /**
         * SimulateRequest
         * @description Policy levers; values are deltas vs a stylized baseline unless noted.
         */
        SimulateRequest: {
            /**
             * Top Marginal Rate Ppt
             * @description Change in top statutory marginal rate (percentage points).
             * @default 0
             */
            top_marginal_rate_ppt: number;
            /**
             * Corporate Rate Ppt
             * @description Change in corporate income tax rate (percentage points).
             * @default 0
             */
            corporate_rate_ppt: number;
            /**
             * Payroll Combined Ppt
             * @description Combined employer+employee payroll tax change (percentage points).
             * @default 0
             */
            payroll_combined_ppt: number;
            /**
             * Discretionary Spending Pct Gdp Ppt
             * @description Change in primary discretionary outlays as share of GDP (percentage points).
             * @default 0
             */
            discretionary_spending_pct_gdp_ppt: number;
            /**
             * Regulatory Cost Index
             * @description Index on economy-wide compliance cost (1 = baseline).
             * @default 1
             */
            regulatory_cost_index: number;
            /**
             * Tcja Sunset Year
             * @description If set, models partial individual provisions expiring in that year (2025–2035).
             */
            tcja_sunset_year?: number | null;
            /**
             * Tcja Sunset Depth
             * @description How much of TCJA individual provisions are assumed to sunset.
             * @default none
             * @enum {string}
             */
            tcja_sunset_depth: "none" | "partial" | "full";
            /**
             * Luxury Consumption Fee Ppt
             * @description Illustrative fee on high-end consumption (percentage points), scenario use.
             * @default 0
             */
            luxury_consumption_fee_ppt: number;
            /**
             * Tariff Proxy Ppt
             * @description Illustrative average effective tariff proxy (percentage points).
             * @default 0
             */
            tariff_proxy_ppt: number;
        };
        /** SimulateResponse */
        SimulateResponse: {
            /**
             * Revenue Change 10Yr Bn
             * @description Illustrative 10-year change in federal receipts (billions USD, undiscounted sum).
             */
            revenue_change_10yr_bn: number;
            /** Outlay Change 10Yr Bn */
            outlay_change_10yr_bn: number;
            /** Deficit Change 10Yr Bn */
            deficit_change_10yr_bn: number;
            /**
             * Gdp Level Year5 Pct
             * @description Illustrative GDP level effect in year 5 vs baseline (%).
             */
            gdp_level_year5_pct: number;
            /** Median Household Income Change Pct */
            median_household_income_change_pct: number;
            /** Distributional */
            distributional: components["schemas"]["QuintileImpact"][];
            /** Model Version */
            model_version: string;
            /** Data Vintage */
            data_vintage: string;
            /** Disclaimer */
            disclaimer: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    simulate_policy_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_presets_simulate_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
